const GET_REQUEST = "GET_REQUEST";
const GET_SUCCESS = "GET_SUCCESS";
const GET_ERROR = "GET_ERROR";

const USER_SIGNIN = "USER_SIGNIN";
const USER_SIGNOUT = "USER_SIGNOUT";

const ADD_TO_CART = "ADD_TO_CART";
const GET_FAIL = "GET_FAIL";



export {GET_REQUEST, GET_SUCCESS, GET_ERROR, USER_SIGNIN, USER_SIGNOUT, ADD_TO_CART, GET_FAIL}